apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: binayokbhowmikxp/techtrends:latest
        name: techtrends
        ports:
          - containerPort: 3111
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "120Mi"
        readinessProbe:
         httpGet:
          path: /healthz
          port: 3111
        livenessProbe:
         httpGet:
          path: /healthz
          port: 3111
